# Generated by Django 5.2.11 on 2026-03-07 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('success_rate', models.FloatField(default=0)),
                ('failure_rate', models.FloatField(default=0)),
                ('avg_latency', models.FloatField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
