# Generated by Django 5.2.11 on 2026-02-18 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('merchant_type', models.CharField(choices=[('individual', 'Individual'), ('sole_proprietor', 'Sole Proprietor'), ('llc', 'Limited Liability Company'), ('corporation', 'Corporation')], default='individual', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_docs', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('opay', 'OPay')], max_length=50)),
                ('secret_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'merchant API key',
                'verbose_name_plural': 'merchant API keys',
                'unique_together': {('merchant', 'provider')},
            },
        ),
    ]
