# Generated by Django 5.2.11 on 2026-02-28 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantaccountkey',
            old_name='merchant_api_key',
            new_name='secret_key',
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], db_index=True, default='starter', max_length=20)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('requests_per_hour', models.IntegerField(default=1000)),
                ('requests_per_day', models.IntegerField(default=10000)),
                ('burst_allowance', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(help_text='Associated merchant', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Rate Limit',
                'verbose_name_plural': 'Rate Limits',
                'indexes': [models.Index(fields=['tier'], name='merchants_r_tier_982bff_idx')],
            },
        ),
    ]
