# Generated by Django 5.2.11 on 2026-02-18 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccountKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('sandbox', 'Sandbox')], default='live', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_keys', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'merchant account key',
                'verbose_name_plural': 'merchant account keys',
            },
        ),
    ]
