# Generated by Django 5.2.11 on 2026-02-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_rename_merchant_api_key_merchantaccountkey_secret_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateLimit',
        ),
    ]
