# Generated by Django 5.2.11 on 2026-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantaccountkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(choices=[('sole proprietor', 'Sole Proprietor'), ('llc', 'Limited Liability Company'), ('corporation', 'Corporation')], default='sole proprietor', max_length=20),
        ),
    ]
