# Generated by Django 5.2.11 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_merchant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='live_mode',
            field=models.BooleanField(default=False),
        ),
    ]
