# Generated by Django 5.2.11 on 2026-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchant_live_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
