# Generated by Django 5.2.11 on 2026-02-28 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0003_delete_ratelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_secret', models.CharField(editable=False, max_length=128)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('sandbox', 'Sandbox')], default='live', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'unique_together': {('merchant', 'client_name')},
            },
        ),
        migrations.CreateModel(
            name='APIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'API Usage Record',
                'verbose_name_plural': 'API Usage Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], db_index=True, default='starter', max_length=20)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('requests_per_hour', models.IntegerField(default=1000)),
                ('requests_per_day', models.IntegerField(default=10000)),
                ('burst_allowance', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(help_text='Associated merchant APIClient', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'Rate Limit',
                'verbose_name_plural': 'Rate Limits',
                'indexes': [models.Index(fields=['tier'], name='api_apirate_tier_b78871_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('opay', 'OPay')], max_length=50)),
                ('secret_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_keys', to='api.apiclient')),
            ],
            options={
                'verbose_name': 'Provider API Key',
                'verbose_name_plural': 'Provider API Keys',
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
