# Generated by Django 5.2.11 on 2026-02-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiratelimit',
            name='merchant',
        ),
        migrations.AddField(
            model_name='apiratelimit',
            name='client',
            field=models.OneToOneField(default='', help_text='Associated merchant APIClient', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to='api.apiclient'),
            preserve_default=False,
        ),
    ]
