# Generated by Django 5.2.11 on 2026-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='client_secret',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='environment',
            field=models.CharField(choices=[('live', 'Live'), ('Sandbox', 'sandbox')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiratelimit',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], db_index=True, default='starter', max_length=20),
        ),
    ]
