# Generated by Django 5.2.11 on 2026-03-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apiclient_client_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiclient',
            old_name='client_id',
            new_name='client_public_key',
        ),
        migrations.RenameField(
            model_name='apiclient',
            old_name='client_secret',
            new_name='client_secret_key',
        ),
    ]
