# Generated by Django 5.2.11 on 2026-03-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_client_id_apiclient_client_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagerecord',
            name='request_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
