# Generated by Django 5.2.11 on 2026-03-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiusagerecord_request_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.apiclient')),
            ],
            options={
                'unique_together': {('client', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='MerchantProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField()),
                ('credential_type', models.CharField(default='api_key', max_length=50)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.clientprovider')),
            ],
        ),
    ]
