# Generated by Django 5.2.11 on 2026-03-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clientprovider_merchantprovidercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprovider',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('opay', 'OPay')], max_length=50),
        ),
    ]
