# Generated by Django 5.2.11 on 2026-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clientprovider_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MerchantProviderCredential',
            new_name='ClientProviderCredential',
        ),
    ]
