# Generated by Django 5.2.11 on 2026-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_merchantprovidercredential_clientprovidercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='environment',
            field=models.CharField(choices=[('live', 'Live'), ('sandbox', 'Sandbox')], default='live', max_length=20),
        ),
    ]
