# Generated by Django 5.2.11 on 2026-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_apiclient_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='live_mode',
            field=models.BooleanField(default=True),
        ),
    ]
