# Generated by Django 5.2.11 on 2026-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_apiclient_live_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclient',
            name='live_mode',
        ),
        migrations.AddField(
            model_name='apiclient',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
