# Generated by Django 5.2.11 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_apiclient_live_mode_apiclient_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprovider',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('paypal', 'Paypal'), ('flutterwave', 'Flutterwave'), ('fincra', 'Fincra'), ('nomba', 'Nomba'), ('opay', 'OPay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='providerapikey',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('paypal', 'Paypal'), ('flutterwave', 'Flutterwave'), ('fincra', 'Fincra'), ('nomba', 'Nomba'), ('opay', 'OPay')], max_length=50),
        ),
    ]
