# Generated by Django 5.2.11 on 2026-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('abandoned', 'Abandoned')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionattempt',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('abandoned', 'Abandoned')], default='processing', max_length=20),
        ),
    ]
