# Generated by Django 5.2.11 on 2026-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='latency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latency in milliseconds for the transaction processing', max_digits=10, null=True),
        ),
    ]
