# Generated by Django 5.2.11 on 2026-03-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_merchant_business_type'),
        ('transactions', '0004_transaction_latency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to='merchants.merchant'),
        ),
    ]
