# Generated by Django 5.2.11 on 2026-03-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_clientprovider_provider_and_more'),
        ('transactions', '0005_alter_transaction_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiclient_transactions', to='api.apiclient'),
        ),
    ]
