# Generated by Django 5.2.11 on 2026-03-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_api_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('payout', 'Payout'), ('refund', 'Refund'), ('topup', 'Topup')], default='collection', max_length=20),
        ),
    ]
