# Generated by Django 5.2.11 on 2026-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, default='', help_text='Payment channel used, e.g. card, bank_transfer, ussd', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
