# Generated by Django 5.2.11 on 2026-03-20 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_clientprovider_provider_and_more'),
        ('merchants', '0006_merchant_business_type'),
        ('transactions', '0008_alter_transaction_amount_alter_transaction_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='final_provider',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='preferred_provider',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_source',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.apiclient'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('payout', 'Payout'), ('refund', 'Refund'), ('topup', 'Topup')], max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(blank=True, help_text='card, bank_transfer, ussd', max_length=50, null=True)),
                ('transaction_source', models.CharField(choices=[('api', 'API'), ('payment_link', 'Payment Link'), ('checkout', 'Checkout'), ('pos', 'POS')], default='api', max_length=20)),
                ('preferred_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('final_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='transactions.transaction')),
            ],
        ),
    ]
