# Generated by Django 5.2.11 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_transaction_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
