# Generated by Django 5.2.11 on 2026-03-21 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_collectiontransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiontransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
