# Generated by Django 5.2.11 on 2026-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_collectiontransaction_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
