# Generated by Django 5.2.11 on 2026-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontransaction',
            name='payment_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
