

AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_REQUEST = "INVALID_REQUEST"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
DUPLICATE_REQUEST = "DUPLICATE_REQUEST"
SERVER_ERROR = "SERVER_ERROR"